[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  [functions.timeout]
  # Set timeout to 10 seconds
  timeout = 10

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

